name: Release To Pypi

on:
  release:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    environment:
      name: dmp-pypi
      url: https://pypi.org/p/mcp-project-context-server

    steps:
      - name: Publish package distributions to PyPI
        if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true
